### ISSUE TITLE
やりたいFCゲームを３つ書け！

### ISSUE THREAD

**Issue by aireiya** [2016-game-developers-morijyobi/FamiconGameSelection#44]
山谷セレクション
★★★ランペルール【シミュレーション】
★★バトルストーム【シミュレーション】
★ギャラクシアン【シューティング】
クソゲーセレクション
天才バカボン【アクション】

**Comment by hkamu** [comment]
樋口
シミュレーション:ファイアーエムブレム 暗黒竜と光の剣　★★
テーブル：いただきストリート　　　　　　　　　　　　★★★
RPG:半熟英雄　　　　　　　　　　　　　　　　　  ★
アクション：カラテカ（クソゲー）

**Comment by sugaha** [comment]
菅原
★★イースⅡ（ＲＰＧ）
★★★イース（ＲＰＧ）
★マリオブラザーズ（アクション）
クソゲー
シャドウゲイト(アドベンチャー)

**Comment by at313** [comment]
荒川
★・レッキングクルー(アクション)
★★★・スペランカー(アクション)
★★・イース(RPG)
・シャドウゲイト(アドベンチャー)(クソゲー)

**Comment by mocosyun** [comment]
魔界村
ディグダグ
ツインビー

**Comment by cocytus01** [comment]
山口
・★★ぷよぷよ　　：パズル　
・★★★MOTHER　  ：RPG
・★ドクターマリオ：パズル
・【クソゲー】星をみるひと：RPG

**Comment by tayuhi** [comment]
髙橋　雄飛
カケフくんのジャンプ天国　　アクションゲーム　　　　　　クソゲー
☆☆☆シャドウゲイト　　　　　　  アドベンチャ－ゲーム　　　　
☆☆スウィートホーム 　　　　　ロールプレイングゲーム
☆東方見文録　　　　　　　 アドベンチャーゲーム

**Comment by Ryo779** [comment]
堀井
☆☆☆ロックマン（アクション）
☆☆ボンバーマン（アクション）
☆麻雀（テーブル）
スペランカー（クソゲー）

**Comment by MatuzawaGaku** [comment]
松澤
★バルーンファイト                  アクションゲーム
★★谷川浩司の将棋指南          テーブルゲーム
★★★スペースインベーダー          シューティングゲーム
クソゲーセレクション
・ミシシッピー殺人事件          アドベンチャーゲーム

**Comment by ishida-takumi** [comment]
石田
・★★ジッピーレース（レース）
・★いただきストリート(テーブル) 
・★★★スぺランカーⅡ勇者への挑戦（アクション）
トランスフォーマー　コンボイの謎（クソゲーアクション）

**Comment by yui0722** [comment]
聖人
・★ミッキーマウス 不思議の国の大冒険　(アクション)
・★★わんぱくダック夢冒険　(アクション)
・★★★チップとデールの大作戦2　(アクション)
・クソゲー　CITY ADVENTURE タッチ MYSTERY OF TRIANGLE　（アクション）

**Comment by toshikei** [comment]
藤澤
★★★半熟英雄　　　　　RPG
★★BUBLLE BOBLLE　アクション
★MOTHER　　　　　RPG
高橋名人の冒険島　アクション(クソゲー)

**Comment by anirori** [comment]
細田
☆☆☆ロックマン：アクション
☆半熟英雄：RPG
☆☆スぺランカー：アクション
クソゲー
アトランチスの謎：アクション

**Comment by mocosyun** [comment]
竣亮
たけしの挑戦状　アクション　糞　
ぷよぷよ　パズルゲーム☆☆
チップとデール大作戦　アクション　☆
川のぬし釣り　アクション　☆☆☆

**Comment by E-tiru** [comment]
磯野
☆☆☆ボンバーキング：アクション　※クソゲー
★☆☆ゴルフ：スポーツ
★★★エキサイトバイク：レース
★★☆ボンバーマン：アクション

**Comment by hosokawa9360** [comment]
ご回答ありがとう
